version: '3' # Specify version of compose to be used
services: # Each subkey creates a Docker container (i.e. service)
  flasky: # Each subkey are put into docker build and docker run
    build: . # Looks for a Dockerfile in the current dir and build that
    ports:
      - "8000:5000"
    env_file: .env-flasky
    links:
      - mysql:mysql-server
    restart: always
    image: aldosebastian/blogging
    container_name: blogging_service
  mysql:
    image: "mysql/mysql-server:5.7" # Download and use mysql image from Docker website
    env_file: .env-mysql
    restart: always
    ports:
      - "5423:3306"
    volumes:
      - /home/aldo/bloggingDB/data:/var/lib/mysql
    container_name: blogging_service_db
  # The links subkey ensures mysql will start first before flasky