"""empty message

Revision ID: b9e6e7d9e4b3
Revises: 075d9ab05562
Create Date: 2022-06-02 12:15:18.600584

"""
from alembic import op
import sqlalchemy as sa
from config import Config

# revision identifiers, used by Alembic.
revision = 'b9e6e7d9e4b3'
down_revision = '075d9ab05562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_comments_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    with op.batch_alter_table('follows', schema=None, naming_convention=Config.NAMING_CONVENTION) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_follows_following_id_users'), 'users', ['following_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_follows_follower_id_users'), 'users', ['follower_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    with op.batch_alter_table('follows', schema=None, naming_convention=Config.NAMING_CONVENTION) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_follows_following_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_follows_follower_id_users'), type_='foreignkey')
    # ### end Alembic commands ###
