"""empty message

Revision ID: 98a6a60f6c4d
Revises: 1b24ccdf0755
Create Date: 2022-05-28 17:05:17.411266

"""
from alembic import op
import sqlalchemy as sa
from config import Config

# revision identifiers, used by Alembic.
revision = '98a6a60f6c4d'
down_revision = 'd0608c6ee42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('_alembic_tmp_roles')
    #with op.batch_alter_table('follows', schema=None, naming_convention=Config.NAMING_CONVENTION) as batch_op:
    #    batch_op.create_foreign_key(batch_op.f('fk_follows_following_id_users'), 'users', ['following_id'], ['id'])
    #    batch_op.create_foreign_key(batch_op.f('fk_follows_follower_id_users'), 'users', ['follower_id'], ['id'])
    #    batch_op.drop_column('followed_id')
    #    batch_op.drop_constraint("pk_follows","follows")
    #    batch_op.create_primary_key("pk_follows", "follows", ["follower_id","following_id"])
    #op.drop_constraint()
    #op.create_primary_key("pk_follows", "follows")
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_posts_author_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('follows', schema=None, naming_convention=Config.NAMING_CONVENTION) as batch_op:
    #    batch_op.add_column(sa.Column('followed_id', sa.INTEGER(), nullable=False))
    #    batch_op.drop_constraint(batch_op.f('fk_follows_following_id_users'), type_='foreignkey')
    #    batch_op.drop_constraint(batch_op.f('fk_follows_follower_id_users'), type_='foreignkey')

    #op.create_table('_alembic_tmp_roles',
    #sa.Column('id', sa.INTEGER(), nullable=False),
    #sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    #sa.Column('default', sa.BOOLEAN(), nullable=True),
    #sa.Column('permissions', sa.INTEGER(), nullable=True),
    #sa.PrimaryKeyConstraint('id')
    #)
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
