"""empty message

Revision ID: 4acef528e940
Revises: a1e614f0fe66
Create Date: 2022-06-08 15:42:02.642253

"""
from alembic import op
import sqlalchemy as sa
from config import Config

# revision identifiers, used by Alembic.
revision = '4acef528e940'
down_revision = 'a1e614f0fe66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None, naming_convention=Config.NAMING_CONVENTION) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None, naming_convention=Config.NAMING_CONVENTION) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
