"""empty message

Revision ID: 779318bcd6c1
Revises: e5d16599a7c4
Create Date: 2022-08-22 09:17:02.797037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779318bcd6c1'
down_revision = 'e5d16599a7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_votes_post_id_posts')),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], name=op.f('fk_votes_voter_id_users')),
    sa.PrimaryKeyConstraint('voter_id', 'post_id', name=op.f('pk_votes'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('votes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.INTEGER(), nullable=True))

    op.drop_table('votes')
    # ### end Alembic commands ###
