"""empty message

Revision ID: cbcece3611e6
Revises: 4acef528e940
Create Date: 2022-08-20 12:30:15.371622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbcece3611e6'
down_revision = '4acef528e940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_column('trigger')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('title_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('title_html')
        batch_op.drop_column('title')

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
